[package]
name = "wasm-test"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "19.0.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11.0"
