[package]
name = "lumos-core"
version = "0.1.0"
edition = "2021"
description = "Core functionality for Lumos-DB, a data platform for AI Agents"
authors = ["Lumos Team"]
license = "MIT"

[dependencies]
# SQLite integration
rusqlite = { version = "0.29.0", features = ["bundled"] }

# DuckDB integration
duckdb = "0.8.1"

# Utilities
thiserror = "1.0.47"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
chrono = "0.4.26"
log = "0.4.19"
env_logger = "0.10.0"
tokio = { version = "1.29.1", features = ["full"] }
rand = "0.8.5"

[dev-dependencies]
tempfile = "3.8.0"
criterion = "0.5.1"
tokio-test = "0.4.3"

[[bench]]
name = "query_benchmark"
harness = false
