version: '1.0'
name: "MongoDB WASM插件示例"
description: "使用WebAssembly MongoDB插件从CSV文件提取数据，转换后加载到MongoDB"

# 启用WebAssembly插件系统
wasm_plugins:
  enabled: true
  plugins_dir: "./plugins"  # WebAssembly插件目录
  auto_load: true           # 自动加载插件

# 定义任务
jobs:
  - name: "csv-extract"
    type: "extractor"
    extractor_type: "csv"  # 使用内置CSV提取器
    options:
      file_path: "./data/sample.csv"
      has_header: true
      delimiter: ","
    next: "transform-data"
  
  - name: "transform-data"
    type: "transformer"
    transformer_type: "default"  # 使用内置转换器
    options:
      operations:
        - type: "rename"
          from: "id"
          to: "_id"
        - type: "add_field"
          field: "processed_at"
          value: "${NOW}"  # 使用时间戳替换值
    next: "load-to-mongodb"
  
  - name: "load-to-mongodb"
    type: "loader"
    loader_type: "mongodb"  # 使用MongoDB WebAssembly插件
    options:
      connection_string: "mongodb://localhost:27017"
      database: "sample_db"
      collection: "sample_data"
      mode: "replace"  # replace或append模式 